# @generated
load("@antlir//antlir/antlir2/package_managers/dnf/rules:rpm.bzl", "rpm")
load("@antlir//antlir/antlir2/package_managers/dnf/rules:xml.bzl", "xml")
rpm(name='0-5.1-3.el10_0.noarch-fcaf5', rpm_name='python3-zope-exceptions', epoch=0, version='5.1', release='3.el10_0', arch='noarch', url='https://mirror.facebook.net/fedora/epel/10/Everything/x86_64/Packages/p/python3-zope-exceptions-5.1-3.el10_0.noarch.rpm', xml=':0-5.1-3.el10_0.noarch-fcaf5--xml', sha1=None, sha256='fcaf5ca3cd65e1c2f5b1bb027c65d78d027a156c0a671081725295c1a7b3131a', visibility=['//snapshot/rpm/centos10/...'])
xml(name='0-5.1-3.el10_0.noarch-fcaf5--xml', primary='<package type="rpm">\n  <name>python3-zope-exceptions</name>\n  <arch>noarch</arch>\n  <version epoch="0" ver="5.1" rel="3.el10_0"/>\n  <checksum type="sha256" pkgid="YES">fcaf5ca3cd65e1c2f5b1bb027c65d78d027a156c0a671081725295c1a7b3131a</checksum>\n  <summary>Zope Exceptions</summary>\n  <description>This package contains exception interfaces and implementations which are so\ngeneral purpose that they don\'t belong in Zope application-specific packages.</description>\n  <packager>Fedora Project</packager>\n  <url>https://zopeexceptions.readthedocs.io/</url>\n  <time file="1737388507" build="1737386760"/>\n  <size package="48570" installed="157807" archive="165448"/>\n  <location href="Packages/fcaf5ca3cd65e1c2f5b1bb027c65d78d027a156c0a671081725295c1a7b3131a/python3-zope-exceptions-0:5.1-3.el10_0.noarch.rpm"/>\n  <format>\n    <rpm:license>ZPL-2.1</rpm:license>\n    <rpm:vendor>Fedora Project</rpm:vendor>\n    <rpm:group>Unspecified</rpm:group>\n    <rpm:buildhost>buildvm-x86-04.iad2.fedoraproject.org</rpm:buildhost>\n    <rpm:sourcerpm>python-zope-exceptions-5.1-3.el10_0.src.rpm</rpm:sourcerpm>\n    <rpm:header-range start="4504" end="14745"/>\n    <rpm:provides>\n      <rpm:entry name="python-zope-exceptions" flags="EQ" epoch="0" ver="5.1" rel="3.el10_0"/>\n      <rpm:entry name="python3-zope-exceptions" flags="EQ" epoch="0" ver="5.1" rel="3.el10_0"/>\n      <rpm:entry name="python3.12-zope-exceptions" flags="EQ" epoch="0" ver="5.1" rel="3.el10_0"/>\n      <rpm:entry name="python3.12dist(zope-exceptions)" flags="EQ" epoch="0" ver="5.1"/>\n      <rpm:entry name="python3dist(zope-exceptions)" flags="EQ" epoch="0" ver="5.1"/>\n    </rpm:provides>\n    <rpm:requires>\n      <rpm:entry name="python(abi)" flags="EQ" epoch="0" ver="3.12"/>\n      <rpm:entry name="python3.12dist(setuptools)"/>\n      <rpm:entry name="python3.12dist(zope-interface)"/>\n    </rpm:requires>\n    <rpm:obsoletes>\n      <rpm:entry name="python3.12-zope-exceptions" flags="LT" epoch="0" ver="5.1" rel="3.el10_0"/>\n    </rpm:obsoletes>\n  </format>\n</package>\n', filelists='<package pkgid="fcaf5ca3cd65e1c2f5b1bb027c65d78d027a156c0a671081725295c1a7b3131a" name="python3-zope-exceptions" arch="noarch">\n  <version epoch="0" ver="5.1" rel="3.el10_0"/>\n  <file type="dir">/usr/lib/python3.12/site-packages/zope</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1-py3.12-nspkg.pth</file>\n  <file type="dir">/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info/INSTALLER</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info/LICENSE.txt</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info/METADATA</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info/WHEEL</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info/namespace_packages.txt</file>\n  <file>/usr/lib/python3.12/site-packages/zope.exceptions-5.1.dist-info/top_level.txt</file>\n  <file type="dir">/usr/lib/python3.12/site-packages/zope/exceptions</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__init__.py</file>\n  <file type="dir">/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/__init__.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/__init__.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/interfaces.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/interfaces.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/log.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/__pycache__/log.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/exceptionformatter.py</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/interfaces.py</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/log.py</file>\n  <file type="dir">/usr/lib/python3.12/site-packages/zope/exceptions/tests</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__init__.py</file>\n  <file type="dir">/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/__init__.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/__init__.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_exceptionformatter.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_log.cpython-312.opt-1.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/__pycache__/test_log.cpython-312.pyc</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/test_exceptionformatter.py</file>\n  <file>/usr/lib/python3.12/site-packages/zope/exceptions/tests/test_log.py</file>\n  <file type="dir">/usr/share/doc/python3-zope-exceptions</file>\n  <file>/usr/share/doc/python3-zope-exceptions/CHANGES.rst</file>\n  <file>/usr/share/doc/python3-zope-exceptions/README.rst</file>\n  <file type="dir">/usr/share/licenses/python3-zope-exceptions</file>\n  <file>/usr/share/licenses/python3-zope-exceptions/COPYRIGHT.txt</file>\n  <file>/usr/share/licenses/python3-zope-exceptions/LICENSE.txt</file>\n</package>\n', other='<package pkgid="fcaf5ca3cd65e1c2f5b1bb027c65d78d027a156c0a671081725295c1a7b3131a" name="python3-zope-exceptions" arch="noarch">\n  <version epoch="0" ver="5.1" rel="3.el10_0"/>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-27" date="1689940800">- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-28" date="1705924800">- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-29" date="1706270400">- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild</changelog>\n  <changelog author="Jerry James &lt;loganjerry@gmail.com&gt; - 5.0.1-1" date="1706529600">- Version 5.0.1\n- Convert License tag to SPDX\n- Modernize the spec file</changelog>\n  <changelog author="Python Maint &lt;python-maint@redhat.com&gt; - 5.0.1-2" date="1717761600">- Bootstrap for Python 3.13</changelog>\n  <changelog author="Python Maint &lt;python-maint@redhat.com&gt; - 5.0.1-3" date="1717934400">- Rebuilt for Python 3.13</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 5.0.1-4" date="1721390400">- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild</changelog>\n  <changelog author="Jerry James &lt;loganjerry@gmail.com&gt; - 5.1-1" date="1721736000">- Version 5.1 (rhbz#2290844)\n- Add patch for python 3.13 compatibility (rhbz#2280553)\n- Minor spec file cleanups</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 5.1-2" date="1737201600">- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild</changelog>\n  <changelog author="Kaleb S. KEITHLEY &lt;kkeithle[at]redhat.com&gt; - 5.1-3" date="1737374400">- rebuild in non-bootstrap</changelog>\n</package>\n')
